config/routes.rb
Rails.application.routes.draw do
  root 'clicks#index'

  resources :clicks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click.rb
class Click < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clicks_controller.rb
class ClicksController < ApplicationController
  before_action :set_click, only: [:show, :edit, :update, :destroy]

  # GET /clicks
  # GET /clicks.json
  def index
    @total = Click.where("created_at > ?", DateTime.now - 1.week).count
    @recent = Click.order(created_at: :desc).limit(5)
  end

  # POST /clicks
  # POST /clicks.json
  def create
    @click = Click.new(click_params)

    respond_to do |format|
      if @click.save
        format.html { redirect_to @click, notice: 'Click was successfully created.' }
        format.json { render :show, status: :created, location: @click }
      else
        format.html { render :new }
        format.json { render json: @click.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_click
      @click = Click.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def click_params
      params.require(:click).permit(:city, :state, :country, :user_agent)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/views/clicks/_form.html.erb
<%= form_with(model: click, local: true) do |form| %>
  <% if click.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(click.errors.count, "error") %> prohibited this click from being saved:</h2>

      <ul>
      <% click.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :user_agent %>
    <%= form.text_field :user_agent %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clicks/edit.html.erb
<h1>Editing Click</h1>

<%= render 'form', click: @click %>

<%= link_to 'Show', @click %> |
<%= link_to 'Back', clicks_path %>

app/views/clicks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>We are all anxious. You're not alone.</h1>

<p>There are <%= @count %> anxious people near you.</p>

<table>
  <thead>
    <tr>
      <th>People like you and me.</th>
    </tr>
  </thead>

  <tbody>
    <% @recent.each do |click| %>
      <tr>
        <td>I'm anxious in <%= click.city %>.</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/clicks/new.html.erb
<h1>New Click</h1>

<%= render 'form', click: @click %>

<%= link_to 'Back', clicks_path %>

app/views/clicks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @click.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @click.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @click.country %>
</p>

<p>
  <strong>User agent:</strong>
  <%= @click.user_agent %>
</p>

<%= link_to 'Edit', edit_click_path(@click) %> |
<%= link_to 'Back', clicks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IAmNotAlone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>